

import type { Drill, Achievement, AchievementData, UserProfile } from './types';
import { parseScoreToPar } from './utils';
import { format } from 'date-fns';

// Developer Note for Audio Files:
// The 'audioUrl' property in the drills below are placeholders.
// To make them work:
// 1. Create a directory: `public/audio/` in your project root.
// 2. Place your actual audio files (e.g., .mp3) in this directory.
// 3. Update the `audioUrl` paths below to reflect your actual file names
//    (e.g., `audioUrl: '/audio/your_audio_file.mp3'`).

export const initialDrills: Drill[] = [
  {
    id: 'd1',
    name: 'Fairway Finder (Directional Control)',
    category: 'Driving',
    difficulty: 'Intermediate',
    description: 'Focus on consistent setup and swing path. Hit 10 drives aiming for a specific fairway target. Note tendencies if misses occur (e.g. consistent right or left).',
    scoringMethodology: '3 points: On fairway. 1 point: Light rough, playable. 0 points: Heavy rough/penalty.',
    icon: 'Target',
    targetsAreaOfPotential: ['drivingAccuracyGeneral', 'fairwayMissRight', 'fairwayMissLeft', 'consistentMissRight', 'consistentMissLeft'],
    maxScore: 30,
  },
  {
    id: 'd1c',
    name: 'Alignment Check & Routine',
    category: 'General Setup',
    difficulty: 'Beginner',
    description: 'Use alignment sticks for feet, hips, and shoulders. Practice your pre-shot routine for 10 shots, focusing on consistent alignment to the target.',
    scoringMethodology: 'Focus on process. 3 points: Felt well aligned. 1 point: Okay. 0 points: Felt off.',
    icon: 'Goal',
    targetsAreaOfPotential: ['alignmentIssue', 'fairwayMissRight', 'fairwayMissLeft'],
    maxScore: 30,
  },
  {
    id: 'd2',
    name: 'Greens in Regulation Challenge',
    category: 'Approach',
    difficulty: 'Intermediate',
    description: 'From 150 yards (or your common approach distance), hit 10 shots to a green. Track how many land on the putting surface.',
    scoringMethodology: '1 point per GIR. Bonus: +1 for within 15ft.',
    icon: 'TrendingUp',
    targetsAreaOfPotential: ['girLow', 'approachConsistency'],
    maxScore: 20,
  },
  {
    id: 'd3',
    name: 'Up and Down Master',
    category: 'Around the Green',
    difficulty: 'Advanced',
    description: 'Place 10 balls in various tricky spots around a green (rough, short-sided). Play each ball until holed out. Aim for 2 shots (up and down).',
    scoringMethodology: '3 points: Up and down in 2 shots. 1 point: Holed in 3 shots. 0 points: 4+ shots.',
    icon: 'Flag',
    targetsAreaOfPotential: ['shortGameScrambling', 'upAndDownLow'],
    maxScore: 30,
  },
  {
    id: 'd4',
    name: 'Short Putt Pressure Test (3-6ft)',
    category: 'Putting',
    difficulty: 'Beginner',
    description: 'From 3, 4, 5, and 6 feet, hit 5 putts from each spot. Focus on routine and making a confident stroke. Track makes from each distance.',
    scoringMethodology: 'Count successful putts. Aim for high conversion rates, especially inside 5ft.',
    icon: 'ListChecks',
    targetsAreaOfPotential: ['putting5ftLowPercentage', 'puttingConsistencyGeneral'],
    maxScore: 20,
  },
  {
    id: 'd5',
    name: 'Distance Control Wedges',
    category: 'Approach',
    difficulty: 'Intermediate',
    description: 'Hit 5 shots each to targets at 30, 50, and 70 yards with your wedges. Focus on consistent carry distances.',
    scoringMethodology: 'Proximity based. 3 points: within 5ft. 1 point: within 10ft. 0 points: outside 10ft.',
    icon: 'TrendingUp',
    targetsAreaOfPotential: ['approachDistanceControl', 'approachMissShort', 'approachMissLong'],
    maxScore: 45,
  },
  {
    id: 'd6',
    name: 'Sand Save Practice',
    category: 'Around the Green',
    difficulty: 'Intermediate',
    description: 'Hit 10 bunker shots to a specific target on the green. Focus on getting the ball out and onto the green.',
    scoringMethodology: '3 points: On green and within 10ft. 1 point: On green. 0 points: Still in bunker or off green.',
    icon: 'Flag',
    targetsAreaOfPotential: ['sandSavesLow', 'shortGameBunker'],
    maxScore: 30,
  },
   {
    id: 'd7',
    name: 'Lag Putting (15-30ft)',
    category: 'Putting',
    difficulty: 'Intermediate',
    description: 'Hit 10 putts from various distances between 15 and 30 feet. Aim to leave the ball within a 3ft circle around the hole.',
    scoringMethodology: '3 points: Inside 3ft circle. 1 point: Inside 6ft circle. 0 points: Outside 6ft.',
    icon: 'ListChecks',
    targetsAreaOfPotential: ['putting10ftLowPercentage', 'putting20ftLowPercentage', 'threePuttHigh', 'puttingDistanceControl'],
    maxScore: 30,
  },
  {
    id: 'd8',
    name: 'Long Range Putting (21+ yards)',
    category: 'Putting',
    difficulty: 'Intermediate',
    description: 'Hit 10 putts from over 60 feet (20+ yards). Focus on getting the first putt to finish within a 6ft radius of the hole.',
    scoringMethodology: '3 points: Inside 6ft. 1 point: Inside 10ft. 0 points: Outside 10ft.',
    icon: 'ListChecks',
    targetsAreaOfPotential: ['putting21plusYardsLowPercentage', 'threePuttHigh', 'puttingDistanceControl'],
    maxScore: 30,
  },
  {
    id: 'd9',
    name: 'The Fairway Gate',
    category: 'Driving',
    difficulty: 'Intermediate',
    description: "Place two headcovers or alignment sticks about 2 feet apart, approximately 3 feet in front of your golf ball, forming a 'gate'. The goal is to start the ball through this gate. This forces a more neutral swing path and helps fix severe slices or hooks. Hit 10 drives.",
    scoringMethodology: '3 points: Ball goes through the gate and lands in the fairway. 1 point: Ball goes through the gate but misses the fairway. 0 points: Ball misses the gate.',
    icon: 'GitCommit',
    targetsAreaOfPotential: ['drivingAccuracyGeneral', 'drivingSlice', 'drivingHook', 'consistentMissRight', 'consistentMissLeft'],
    maxScore: 30,
  },
  {
    id: 'd10',
    name: 'Alternating Shot Shapes',
    category: 'Driving',
    difficulty: 'Advanced',
    description: 'On the driving range, pick a central target. For your first drive, aim to hit a draw. For your second, aim to hit a fade. Alternate for 10 shots. This develops exceptional clubface and path control.',
    scoringMethodology: 'Score out of 10 for successfully executing the intended shot shape, regardless of whether it lands on the target line.',
    icon: 'Shuffle',
    targetsAreaOfPotential: ['drivingAccuracyGeneral', 'shotShaping'],
    maxScore: 10,
  },
  {
    id: 'd11',
    name: 'Find the Fairway Under Pressure',
    category: 'Driving',
    difficulty: 'Intermediate',
    description: 'Imagine the narrowest fairway on your home course. Visualise the out-of-bounds stakes. Go through your full pre-shot routine and hit the shot. Repeat 10 times, focusing on a smooth tempo rather than power.',
    scoringMethodology: 'Count how many of the 10 drives you would feel confident were in play on that specific hole.',
    icon: 'HeartPulse',
    targetsAreaOfPotential: ['drivingAccuracyGeneral', 'drivingPenaltiesHigh'],
    maxScore: 10,
  },
  {
    id: 'd12',
    name: 'Left-Side, Right-Side',
    category: 'Driving',
    difficulty: 'Intermediate',
    description: 'Divide the fairway mentally into a left half and a right half. For the first ball, aim to land it in the left half. For the second ball, aim for the right half. Repeat for 10 pairs of shots. This helps move away from just "hitting the fairway" to "hitting a specific part of it".',
    scoringMethodology: '1 point for each ball that lands in the correct half of the fairway. Total score out of 20.',
    icon: 'GitFork',
    targetsAreaOfPotential: ['drivingAccuracyGeneral', 'consistentMissRight', 'consistentMissLeft'],
    maxScore: 20,
  },
  {
    id: 'd13',
    name: 'First Tee Simulation',
    category: 'Driving',
    difficulty: 'Beginner',
    description: 'Before you hit, step away and fully visualise your first tee shot of a competition round. Go through your entire pre-shot routine from start to finish. The goal is to build a repeatable routine that stands up under pressure. Hit 10 "first tee" shots.',
    scoringMethodology: 'This is process-based. Score yourself out of 10 based on how well you stuck to your routine for each shot.',
    icon: 'PlayCircle',
    targetsAreaOfPotential: ['drivingAccuracyGeneral', 'preShotRoutine'],
    maxScore: 10,
  },
  {
    id: 'd14',
    name: 'Optimise Your Miss',
    category: 'Driving',
    difficulty: 'Advanced',
    description: 'If your typical miss is a slice, aim down the left rough line and try to hit your normal shot, letting it curve back towards the fairway. If you hook, aim down the right rough. This drill teaches you to play with your stock shot shape instead of fighting it. Hit 10 drives.',
    scoringMethodology: 'Score out of 10 for drives that finish in a playable position (fairway or first cut of rough).',
    icon: 'Settings2',
    targetsAreaOfPotential: ['drivingSlice', 'drivingHook'],
    maxScore: 10,
  },
  {
    id: 'd15',
    name: 'Variable Tempo Drives',
    category: 'Driving',
    difficulty: 'Intermediate',
    description: 'Hit 3 drives with what feels like a 70% tempo. Then 3 drives at 90% tempo. Finally, 3 drives at a full 100% "go for it" tempo. Notice how your accuracy and consistency change. This helps you find your optimal, repeatable rhythm.',
    scoringMethodology: 'No score. Use the notes section to record your observations on distance and accuracy for each tempo.',
    icon: 'GaugeCircle',
    targetsAreaOfPotential: ['drivingAccuracyGeneral', 'tempo'],
    maxScore: 0,
  },
  {
    id: 'd16',
    name: 'The "Draw-Back" Slice Fix',
    category: 'Driving',
    difficulty: 'Intermediate',
    description: 'During your takeaway, consciously feel like you are drawing the clubhead back further inside the target line than normal. This promotes an in-to-out swing path to help neutralise a slice. Hit 10 balls.',
    scoringMethodology: 'Focus on ball flight. 3 points for a draw, 1 point for a straight ball, 0 for a slice.',
    icon: 'CornerUpLeft',
    targetsAreaOfPotential: ['drivingSlice', 'consistentMissRight'],
    maxScore: 30,
  },
  {
    id: 'd17',
    name: 'The "Hold-Off" Hook Fix',
    category: 'Driving',
    difficulty: 'Intermediate',
    description: 'During your downswing and through impact, feel like you are preventing your hands from "rolling over" or closing too quickly. This feeling of "holding off" the clubface release will help reduce a hook. Hit 10 balls.',
    scoringMethodology: 'Focus on ball flight. 3 points for a fade, 1 point for a straight ball, 0 for a hook.',
    icon: 'CornerUpRight',
    targetsAreaOfPotential: ['drivingHook', 'consistentMissLeft'],
    maxScore: 30,
  },
  {
    id: 'd18',
    name: 'Awkward Lie Tee Shots',
    category: 'Driving',
    difficulty: 'Advanced',
    description: 'Find an uneven spot on the driving range tee box. Safely hit 5 shots with the ball above your feet, and 5 shots with the ball below your feet. This simulates real on-course situations and improves balance and adaptability.',
    scoringMethodology: 'Score out of 10 for solid contact and a playable result.',
    icon: 'Mountain',
    targetsAreaOfPotential: ['drivingAccuracyGeneral', 'courseManagement'],
    maxScore: 10,
  },
  {
    id: 'd19',
    name: 'The 100-Yard Challenge',
    category: 'Approach',
    difficulty: 'Intermediate',
    description: 'Hit 10 balls from 100 yards to a specific pin. Use a rangefinder or walk off the distance to your landing spots. This drill dials in your scoring club accuracy.',
    scoringMethodology: 'Award points based on proximity. 3 points: inside 10ft. 2 points: inside 20ft. 1 point: on the green. 0 points: off the green.',
    icon: 'Crosshair',
    targetsAreaOfPotential: ['approachConsistency', 'girLow', 'approachDistanceControl'],
    maxScore: 30,
  },
  {
    id: 'd20',
    name: 'Nine-Shot Drill',
    category: 'Approach',
    difficulty: 'Advanced',
    description: 'Pick one target. With one club (e.g., an 8 iron), hit 9 shots: low fade, low straight, low draw; mid-height fade, mid-height straight, mid-height draw; high fade, high straight, high draw. This is the ultimate test of ball flight control.',
    scoringMethodology: 'Score 1 point for each successfully executed shot shape and trajectory. Total score out of 9.',
    icon: 'Grid',
    targetsAreaOfPotential: ['shotShaping', 'approachConsistency'],
    maxScore: 9,
  },
  {
    id: 'd21',
    name: 'Front-Middle-Back Pins',
    category: 'Approach',
    difficulty: 'Intermediate',
    description: 'From a set distance (e.g., 125 yards), hit 3 shots to a front pin location, 3 to a middle pin, and 3 to a back pin. This forces you to change your club or swing length to alter carry distance, not just hit to the middle of the green.',
    scoringMethodology: 'Score 1 point for each shot that lands in the correct third of the green (front, middle, or back).',
    icon: 'MoveVertical',
    targetsAreaOfPotential: ['approachDistanceControl', 'approachMissShort', 'approachMissLong', 'girLow'],
    maxScore: 9,
  },
  {
    id: 'd22',
    name: 'Short-Side Yourself',
    category: 'Approach',
    difficulty: 'Advanced',
    description: "On a practice hole, deliberately aim for the \"wrong\" side of the flag, leaving yourself a very difficult chip (short-sided). Then, play the chip. This drill isn't about scoring well; it's about understanding course management and the penalty for missing in the wrong spot.",
    scoringMethodology: 'No score. Use the notes section to describe the difficulty of the resulting chip.',
    icon: 'AlertTriangle',
    targetsAreaOfPotential: ['courseManagement', 'girLow'],
    maxScore: 0,
  },
  {
    id: 'd23',
    name: 'Uneven Lies Approach',
    category: 'Approach',
    difficulty: 'Intermediate',
    description: 'Find a sloped area near a practice green. Hit 5 shots from an uphill lie, 5 from a downhill lie, 5 with the ball above your feet, and 5 with it below. Use the same club and target for all shots to see how the slope affects ball flight.',
    scoringMethodology: 'Score out of 20 for solid contact and landing on the green.',
    icon: 'TrendingDown',
    targetsAreaOfPotential: ['approachConsistency', 'courseManagement'],
    maxScore: 20,
  },
  {
    id: 'd24',
    name: 'The "Backstop" Drill for Short Misses',
    category: 'Approach',
    difficulty: 'Beginner',
    description: 'If you consistently miss approaches short, this drill helps build confidence to get the ball to the hole. For every shot, your only goal is to have the ball finish past the pin. Pick a club you feel confident with and hit 10 shots.',
    scoringMethodology: '1 point for every shot that finishes past the pin, regardless of left or right.',
    icon: 'ChevronsUp',
    targetsAreaOfPotential: ['approachMissShort', 'approachDistanceControl'],
    maxScore: 10,
  },
  {
    id: 'd25',
    name: 'The "Front Edge" Drill for Long Misses',
    category: 'Approach',
    difficulty: 'Beginner',
    description: 'If you consistently hit approaches long, your only goal for this drill is to land the ball on the front third of the green. This encourages clubbing down or taking something off the swing. Hit 10 shots.',
    scoringMethodology: '1 point for every shot that lands on the front third of the green.',
    icon: 'ChevronsDown',
    targetsAreaOfPotential: ['approachMissLong', 'approachDistanceControl'],
    maxScore: 10,
  },
  {
    id: 'd26',
    name: 'Different Clubs, Same Distance',
    category: 'Approach',
    difficulty: 'Intermediate',
    description: 'Pick a target 75 yards away. Hit 3 shots with your most lofted wedge. Then, hit 3 shots with your next most lofted wedge (e.g., PW instead of SW), using a shorter, more controlled swing. This teaches feel and versatility.',
    scoringMethodology: 'No score. Use notes to compare the trajectory and consistency between the two clubs.',
    icon: 'Replace',
    targetsAreaOfPotential: ['approachConsistency', 'distanceControl'],
    maxScore: 0,
  },
  {
    id: 'd27',
    name: 'Wind Play',
    category: 'Approach',
    difficulty: 'Advanced',
    description: 'On a windy day, practice hitting into the wind, with a crosswind, and downwind. For into-the-wind shots, practice hitting lower, controlled "knock-down" shots. For downwind, practice letting the ball fly high. Hit 5 of each.',
    scoringMethodology: 'Score out of 15 for successfully controlling your trajectory according to the wind.',
    icon: 'Wind',
    targetsAreaOfPotential: ['courseManagement', 'shotShaping', 'approachConsistency'],
    maxScore: 15,
  },
  {
    id: 'd28',
    name: 'First Cut vs. Fairway',
    category: 'Approach',
    difficulty: 'Intermediate',
    description: 'Drop 5 balls in the first cut of rough and 5 balls in the fairway, at the same distance from a target. Hit all 10 shots with the same club. Notice the difference in contact, distance, and spin.',
    scoringMethodology: 'No score. Use notes to compare the results from the two different lies.',
    icon: 'Scissors',
    targetsAreaOfPotential: ['approachConsistency', 'courseManagement', 'girLow'],
    maxScore: 0,
  },
  {
    id: 'd29',
    name: 'Chipping Landing Zones',
    category: 'Around the Green',
    difficulty: 'Beginner',
    description: 'From just off the green, pick a specific spot on the green where you want to land the ball. Place a towel or headcover on that spot. Practice hitting 10 chips to land on the towel and let the ball release to the hole.',
    scoringMethodology: '3 points: Lands on the towel. 1 point: Misses towel but finishes within 6ft of the hole. 0 points: Misses both.',
    icon: 'Copy',
    targetsAreaOfPotential: ['shortGameScrambling', 'upAndDownLow', 'distanceControl'],
    maxScore: 30,
  },
  {
    id: 'd30',
    name: 'High & Soft vs. Low & Running',
    category: 'Around the Green',
    difficulty: 'Intermediate',
    description: 'From the same spot about 15 yards from the pin, hit 5 high-lofted pitches (e.g., with a sand wedge). Then, hit 5 low-running bump-and-run shots (e.g., with an 8 iron). This develops shot versatility.',
    scoringMethodology: 'Score the total proximity of all 10 shots. A lower total score is better.',
    icon: 'ArrowDownUp',
    targetsAreaOfPotential: ['shortGameScrambling', 'courseManagement'],
    maxScore: 0,
  },
  {
    id: 'd31',
    name: 'Bunker: Escape Artist',
    category: 'Around the Green',
    difficulty: 'Beginner',
    description: 'In a practice bunker, your only goal is to get the ball out and onto the putting surface, regardless of where it finishes. This builds confidence for players who struggle with sand. Hit 10 shots.',
    scoringMethodology: 'Score 1 point for every successful escape. Goal is 10/10.',
    icon: 'Shield',
    targetsAreaOfPotential: ['sandSavesLow', 'shortGameBunker'],
    maxScore: 10,
  },
  {
    id: 'd32',
    name: 'The 3-Club Chipping Challenge',
    category: 'Around the Green',
    difficulty: 'Intermediate',
    description: 'Pick a spot to chip from. Hit 3 balls with a sand wedge, 3 with a pitching wedge, and 3 with a 9-iron to the same pin. Observe how the different lofts affect the ball\'s roll-out.',
    scoringMethodology: 'No score. Use notes to record which club was most effective for that particular shot.',
    icon: 'Grip',
    targetsAreaOfPotential: ['shortGameScrambling', 'upAndDownLow'],
    maxScore: 0,
  },
  {
    id: 'd33',
    name: 'Unplayable Lie Recovery',
    category: 'Around the Green',
    difficulty: 'Advanced',
    description: 'Safely drop 5 balls in deep rough near the green and 5 balls in a divot or bare patch. Practice simply advancing the ball onto the green. The goal is to escape trouble, not hole out.',
    scoringMethodology: 'Score 1 point for each shot that ends up on the green.',
    icon: 'Frown',
    targetsAreaOfPotential: ['shortGameScrambling', 'courseManagement'],
    maxScore: 10,
  },
  {
    id: 'd34',
    name: 'Uphill & Downhill Chips',
    category: 'Around the Green',
    difficulty: 'Intermediate',
    description: 'Find a slope around the practice green. Hit 10 chips from an uphill lie to a pin. Then hit 10 from a downhill lie. Notice how the slope affects your setup and the ball\'s reaction on the green.',
    scoringMethodology: 'Score 1 point for each chip that finishes within 6 feet of the hole.',
    icon: 'TrendingUp',
    targetsAreaOfPotential: ['shortGameScrambling', 'upAndDownLow', 'distanceControl'],
    maxScore: 20,
  },
  {
    id: 'd35',
    name: 'Long Bunker Shot',
    category: 'Around the Green',
    difficulty: 'Advanced',
    description: 'Practice 20-30 yard bunker shots. This requires taking less sand and hitting closer to the ball than a greenside bunker shot. Use a less lofted wedge if needed (e.g., gap wedge). Hit 10 shots.',
    scoringMethodology: '3 points: On the green. 1 point: Out of the bunker but off the green. 0 points: Still in bunker.',
    icon: 'SendToBack',
    targetsAreaOfPotential: ['sandSavesLow', 'shortGameBunker', 'distanceControl'],
    maxScore: 30,
  },
  {
    id: 'd36',
    name: 'One-Handed Chipping',
    category: 'Around the Green',
    difficulty: 'Beginner',
    description: 'Hit 10 small chips using only your trail hand (right hand for a right-handed player). Then hit 10 using only your lead hand. This helps feel how each arm contributes to the chipping motion and prevents the "yips".',
    scoringMethodology: 'No score. Focus on the feeling of making solid contact.',
    icon: 'Hand',
    targetsAreaOfPotential: ['shortGameScrambling'],
    maxScore: 0,
  },
  {
    id: 'd37',
    name: 'Pitching Over an Obstacle',
    category: 'Around the Green',
    difficulty: 'Intermediate',
    description: 'Place a bag or alignment stick between you and the hole, about halfway to the pin. Practice hitting high, soft pitch shots over the obstacle. This simulates needing to get over a bunker or rough to a tight pin. Hit 10 shots.',
    scoringMethodology: 'Score based on the final proximity to the pin after clearing the obstacle.',
    icon: 'ArrowUpRight',
    targetsAreaOfPotential: ['shortGameScrambling', 'shotShaping'],
    maxScore: 0,
  },
  {
    id: 'd38',
    name: 'Texas Wedge',
    category: 'Around the Green',
    difficulty: 'Beginner',
    description: "From the fringe or very short fairway just off the green, use your putter to get the ball close. Practice this on 10 different shots where you might normally choose a wedge. It's often the safer, higher-percentage play.",
    scoringMethodology: 'Score as if it were a putt. How many would you be happy with? 10/10.',
    icon: 'CircleDot',
    targetsAreaOfPotential: ['shortGameScrambling', 'courseManagement', 'upAndDownLow'],
    maxScore: 10,
  },
  {
    id: 'd39',
    name: 'The Clock Drill (Short Putts)',
    category: 'Putting',
    difficulty: 'Beginner',
    description: 'Place 12 balls in a circle around a hole, like numbers on a clock, at a distance of 3 feet. Work your way around the circle, trying to make all 12 in a row. If you miss, start over.',
    scoringMethodology: 'Record the number of consecutive putts made before a miss.',
    icon: 'Circle',
    targetsAreaOfPotential: ['putting5ftLowPercentage', 'puttingConsistencyGeneral'],
    maxScore: 12,
  },
  {
    id: 'd40',
    name: 'The Putting Gate',
    category: 'Putting',
    difficulty: 'Intermediate',
    description: "On a 10-foot straight putt, place a 'gate' made of two tees about a foot in front of the ball, just wider than the ball itself. The goal is to roll the ball through the gate, ensuring you start the putt on your intended line.",
    scoringMethodology: 'Hit 10 putts. Score 1 point for each putt that goes through the gate.',
    icon: 'GitCommit',
    targetsAreaOfPotential: ['puttingConsistencyGeneral', 'putting10ftLowPercentage'],
    maxScore: 10,
  },
  {
    id: 'd41',
    name: 'Distance Control Ladder',
    category: 'Putting',
    difficulty: 'Intermediate',
    description: 'Place tees at 10, 20, 30, and 40 feet from a hole. Start at the 10ft tee and hit a putt, trying to get it past the hole but not more than 3 feet past. If successful, move to 20ft, and so on. If you fail, start over at 10ft.',
    scoringMethodology: 'Record the furthest distance you successfully completed.',
    icon: 'MoreVertical',
    targetsAreaOfPotential: ['puttingDistanceControl', 'threePuttHigh', 'puttingLongRange'],
    maxScore: 40,
  },
  {
    id: 'd42',
    name: 'String Line Green Reading',
    category: 'Putting',
    difficulty: 'Advanced',
    description: 'Find a breaking 15-foot putt. Place a string line from your ball to the hole. Observe how the slope of the green moves relative to the straight line. This helps you visualise the true break. Hit 10 putts trying to match the speed to the line.',
    scoringMethodology: 'No score. Use notes to describe your observations on how you read the green.',
    icon: 'Baseline',
    targetsAreaOfPotential: ['greenReading', 'puttingConsistencyGeneral'],
    maxScore: 0,
  },
  {
    id: 'd43',
    name: 'The "3-Foot Circle" Lag Drill',
    category: 'Putting',
    difficulty: 'Intermediate',
    description: 'From 30-40 feet, your goal is not to make the putt, but to lag it into an imaginary 3-foot radius circle around the hole. Place tees to mark the circle. This is the key to eliminating 3-putts. Hit 10 putts.',
    scoringMethodology: 'Score 1 point for each putt that finishes inside the circle.',
    icon: 'CircleDashed',
    targetsAreaOfPotential: ['threePuttHigh', 'puttingLongRange', 'puttingDistanceControl'],
    maxScore: 10,
  },
  {
    id: 'd44',
    name: 'One-Handed Putting',
    category: 'Putting',
    difficulty: 'Beginner',
    description: 'Hit 10 short (5-foot) putts using only your right hand (for a right-hander), then 10 with only your left hand. This isolates the motion of each hand and can help diagnose if one is becoming too dominant and causing pushes or pulls.',
    scoringMethodology: 'No score. Focus on the feel of a square clubface at impact.',
    icon: 'Hand',
    targetsAreaOfPotential: ['puttingConsistencyGeneral', 'putting5ftLowPercentage'],
    maxScore: 0,
  },
  {
    id: 'd45',
    name: 'Uphill / Downhill Speed Test',
    category: 'Putting',
    difficulty: 'Intermediate',
    description: 'Find a practice green with a significant slope. Hit 10 putts of the same length (e.g., 15 feet) directly uphill, then 10 directly downhill. This drills the feel for how much slope affects putting speed.',
    scoringMethodology: 'Use a lag putting scoring method. How many finished within 3 feet?',
    icon: 'TrendingUp',
    targetsAreaOfPotential: ['puttingDistanceControl', 'greenReading'],
    maxScore: 20,
  },
  {
    id: 'd46',
    name: 'Eyes Closed Putting',
    category: 'Putting',
    difficulty: 'Advanced',
    description: 'From 5-6 feet, go through your normal routine, but just before you start your stroke, close your eyes. Hit the putt. This drill enhances your reliance on feel and a pure, repeatable stroke, rather than visual manipulation. Hit 10 putts.',
    scoringMethodology: 'Count how many of the 10 putts you successfully make.',
    icon: 'EyeOff',
    targetsAreaOfPotential: ['putting5ftLowPercentage', 'puttingUnderPressure'],
    maxScore: 10,
  },
  {
    id: 'd47',
    name: 'The "Makeable" Range Challenge',
    category: 'Putting',
    difficulty: 'Intermediate',
    description: 'Hit 3 putts each from 6, 8, and 10 feet. Keep track of your total made out of 9. This is the key scoring range that separates good and great putters.',
    scoringMethodology: 'Total putts made out of 9. Aim to beat your previous score.',
    icon: 'Ruler',
    targetsAreaOfPotential: ['putting10ftLowPercentage'],
    maxScore: 9,
  },
  {
    id: 'd48',
    name: 'The Pressure Putt',
    category: 'Putting',
    difficulty: 'Advanced',
    description: 'You have one ball and must make three 5-foot putts in a row to "win". If you miss any of the three, you "lose" and must start the sequence again. Repeat this entire process 5 times.',
    scoringMethodology: 'Record how many of the 5 "pressure" sequences you successfully completed.',
    icon: 'Star',
    targetsAreaOfPotential: ['puttingUnderPressure', 'putting5ftLowPercentage'],
    maxScore: 5,
  },
  {
    id: 'd49',
    name: 'Pre-Shot Routine Timer',
    category: 'General Setup',
    difficulty: 'Beginner',
    description: 'Use a stopwatch. Time your pre-shot routine from the moment you decide on a club until you start your swing. Do this for 10 shots. The goal is not speed, but consistency. Your routine should take roughly the same amount of time for every shot.',
    scoringMethodology: 'No score. Record your average time and the variance between shots in the notes.',
    icon: 'Timer',
    targetsAreaOfPotential: ['preShotRoutine', 'consistency'],
    maxScore: 0,
  },
  {
    id: 'd50',
    name: 'Posture Check with Club',
    category: 'General Setup',
    difficulty: 'Beginner',
    description: 'Take your normal address position. Then, hold a club up to your back. It should touch three points: the back of your head, your upper back, and your tailbone. If it doesn\'t, adjust your posture until it does. Repeat this 10 times to build muscle memory.',
    scoringMethodology: 'Process-based. Score 1 point for each time you successfully get into the correct posture.',
    icon: 'AlignVerticalJustifyCenter',
    targetsAreaOfPotential: ['setupConsistency', 'posture'],
    maxScore: 10,
  },
  {
    id: 'd51',
    name: 'Ball Position Consistency',
    category: 'General Setup',
    difficulty: 'Beginner',
    description: "Take your stance with a driver, then a mid-iron (7-iron), then a wedge. Use an alignment stick on the ground to mark where the ball is relative to your lead foot's heel. Check for consistency: driver should be off the lead heel, irons progressively further back.",
    scoringMethodology: 'No score. Use notes to confirm if your ball position is correct for each club type.',
    icon: 'Footprints',
    targetsAreaOfPotential: ['setupConsistency', 'ballPosition'],
    maxScore: 0,
  },
  {
    id: 'd52',
    name: 'Pick Your Target',
    category: 'General Setup',
    difficulty: 'Beginner',
    description: 'Before every shot on the range, pick the smallest possible target (e.g., a specific yardage marker, a flag, a single tree). Do not just hit into the open range. This trains your focus and makes practice more like real golf. Hit 20 shots, each with a unique, specific target.',
    scoringMethodology: '1 point for every shot where you successfully picked a specific target before starting your routine.',
    icon: 'LocateFixed',
    targetsAreaOfPotential: ['courseManagement', 'focus'],
    maxScore: 20,
  },
  {
    id: 'd53',
    name: 'Grip Pressure Awareness',
    category: 'General Setup',
    difficulty: 'Beginner',
    description: 'On a scale of 1 (holding a bird) to 10 (squeezing as hard as possible), your grip pressure should be around a 3-4. Hit 10 shots with a mid-iron, focusing solely on maintaining this light, consistent pressure throughout the swing.',
    scoringMethodology: 'No score. Note how this affects your ball striking and tension levels.',
    icon: 'MousePointer',
    targetsAreaOfPotential: ['setupConsistency', 'tempo', 'grip'],
    maxScore: 0,
  },
  {
    id: 'd54',
    name: 'Start Line Visualisation',
    category: 'General Setup',
    difficulty: 'Intermediate',
    description: 'Stand behind your ball and pick an intermediate target (a leaf, a spot of discoloured grass) on your target line, about 1-3 feet in front of the ball. All you need to do is start the ball over this spot. Practice this visualisation and execution for 10 shots.',
    scoringMethodology: '1 point for each shot that starts over the intermediate target.',
    icon: 'Eye',
    targetsAreaOfPotential: ['alignmentIssue', 'focus', 'preShotRoutine'],
    maxScore: 10,
  },
  {
    id: 'd55',
    name: 'Weight Distribution Check',
    category: 'General Setup',
    difficulty: 'Beginner',
    description: 'At address, feel your weight distribution. It should be 50/50 between your feet for most shots. For short chips, feel more weight on your front foot (e.g., 60/40). For drives, feel slightly more on your back foot. Check this for 10 swings without a ball.',
    scoringMethodology: 'Process-based. Score yourself on how well you could feel and control your weight distribution.',
    icon: 'Scale',
    targetsAreaOfPotential: ['setupConsistency', 'balance'],
    maxScore: 10,
  },
  {
    id: 'd56',
    name: 'Post-Shot Routine',
    category: 'General Setup',
    difficulty: 'Intermediate',
    description: 'After every shot on the range (good or bad), take a moment to hold your finish and reflect. If it was good, what did it feel like? If bad, what was the likely cause? This prevents mindlessly hitting balls and builds awareness. Practice for 20 shots.',
    scoringMethodology: '1 point for every shot where you successfully completed a post-shot reflection before hitting the next ball.',
    icon: 'BookOpen',
    targetsAreaOfPotential: ['focus', 'courseManagement'],
    maxScore: 20,
  },
  {
    id: 'd57',
    name: 'Mirror/Camera Swing Check',
    category: 'General Setup',
    difficulty: 'Intermediate',
    description: 'If possible, set up your phone to record your swing from down-the-line and face-on angles. Alternatively, use a mirror or a window reflection. Check key positions: setup, top of backswing, impact.',
    scoringMethodology: 'No score. Use the notes section to record one key takeaway from reviewing your swing.',
    icon: 'Video',
    targetsAreaOfPotential: ['swingMechanics', 'setupConsistency'],
    maxScore: 0,
  },
  {
    id: 'd58',
    name: 'Breathing for Tempo',
    category: 'General Setup',
    difficulty: 'Beginner',
    description: 'Before you take the club back, take a slow, deep breath in, and start your backswing as you slowly exhale. This simple action can reduce tension and smooth out a quick or jerky tempo. Practice this on 10 full swings.',
    scoringMethodology: 'No score. Note the effect on your rhythm and ball contact.',
    icon: 'Wind',
    targetsAreaOfPotential: ['tempo', 'preShotRoutine', 'puttingUnderPressure'],
    maxScore: 0,
  },
  {
    id: 'd59',
    name: 'Build-Up Speed Swings',
    category: 'Driving',
    difficulty: 'Beginner',
    description: 'Make 10 swings without a ball. Start with a very slow, controlled 50% speed swing, focusing on perfect mechanics. Gradually build up by 10% each swing until you are at full speed, feeling the connection and sequence of the swing.',
    scoringMethodology: 'No score. Use the notes section to record how your balance and swing path felt at different speeds.',
    icon: 'TrendingUp',
    targetsAreaOfPotential: ['tempo', 'swingMechanics'],
    maxScore: 0,
  },
  {
    id: 'd60',
    name: 'The "Draw & Fade" Fairway',
    category: 'Driving',
    difficulty: 'Advanced',
    description: 'Mentally split the fairway in two. For the right half, you must hit a draw that starts right and curves back. For the left half, you must hit a fade that starts left and curves back. Hit 5 shots for each shape. This is an advanced control drill.',
    scoringMethodology: '2 points for a successful shape that lands in the correct half. 1 point for the correct shape that misses. 0 for the wrong shape. Max score of 20.',
    icon: 'Spline',
    targetsAreaOfPotential: ['shotShaping', 'drivingAccuracyGeneral'],
    maxScore: 20,
  },
  {
    id: 'd61',
    name: 'Walk-In Routine',
    category: 'Driving',
    difficulty: 'Intermediate',
    description: 'Practice your entire routine starting from 10 feet behind the ball. Select your target, walk into the shot, get set up, and hit. Do this for 10 drives. The goal is to make the transition from seeing the shot to executing it feel seamless.',
    scoringMethodology: 'Score yourself out of 10 on how committed and comfortable you felt over each shot after walking in.',
    icon: 'Footprints',
    targetsAreaOfPotential: ['preShotRoutine', 'focus'],
    maxScore: 10,
  },
  {
    id: 'd62',
    name: 'Driver Off the Deck',
    category: 'Driving',
    difficulty: 'Advanced',
    description: 'For advanced players looking to improve ball striking. On the range, place the ball on a perfect fairway lie and attempt to hit your driver without a tee. This requires a precise, slightly upward angle of attack. Hit 5-10 shots.',
    scoringMethodology: 'No score. Focus purely on making solid contact. Use notes to describe the feeling and result.',
    icon: 'ArrowDown',
    targetsAreaOfPotential: ['swingMechanics', 'ballStriking'],
    maxScore: 0,
  },
  {
    id: 'd63',
    name: 'Minimum Carry Distance',
    category: 'Driving',
    difficulty: 'Intermediate',
    description: 'Identify a target on the range that represents a minimum carry distance you need (e.g., to clear a hazard). Hit 10 drives with the sole focus of carrying the ball past that marker. This is about ensuring your "bad" shots are still functional.',
    scoringMethodology: 'Count how many of the 10 shots successfully carry the required distance.',
    icon: 'Plane',
    targetsAreaOfPotential: ['drivingDistance', 'courseManagement'],
    maxScore: 10,
  },
  {
    id: 'd64',
    name: 'High Tee vs. Low Tee',
    category: 'Driving',
    difficulty: 'Beginner',
    description: 'Hit 5 drives with the ball teed up higher than normal. Then hit 5 drives with it teed up lower than normal. Note the difference in launch angle and spin. This helps understand how tee height affects ball flight.',
    scoringMethodology: 'No score. Record your observations on trajectory and distance for each tee height.',
    icon: 'ArrowDownUp',
    targetsAreaOfPotential: ['drivingDistance', 'shotShaping'],
    maxScore: 0,
  },
  {
    id: 'd65',
    name: 'Post-Penalty Recovery',
    category: 'Driving',
    difficulty: 'Intermediate',
    description: 'Imagine you just hit your first drive out of bounds. Take a moment, go through your calming routine (e.g., deep breath), and then hit your "provisional" ball. The goal is to make the next swing a good one. Repeat this scenario 5 times.',
    scoringMethodology: 'Score each "provisional" shot out of 3 (3=perfect, 2=good, 1=playable, 0=poor).',
    icon: 'Undo2',
    targetsAreaOfPotential: ['mentalGame', 'drivingPenaltiesHigh'],
    maxScore: 15,
  },
  {
    id: 'd66',
    name: 'Closed Stance Hook Fix',
    category: 'Driving',
    difficulty: 'Intermediate',
    description: 'To combat a hook, deliberately set up with your feet, hips, and shoulders aimed slightly left of the target (for a right-hander). This "open" stance makes it easier to swing the club on a path that promotes a fade or straight shot. Hit 10 drives.',
    scoringMethodology: 'Focus on ball flight. 3 points for a fade, 1 point for straight, 0 for a hook.',
    icon: 'Footprints',
    targetsAreaOfPotential: ['drivingHook', 'consistentMissLeft'],
    maxScore: 30,
  },
  {
    id: 'd67',
    name: 'Open Stance Slice Fix',
    category: 'Driving',
    difficulty: 'Intermediate',
    description: 'To combat a slice, deliberately set up with your feet, hips, and shoulders aimed slightly right of the target (for a right-hander). This "closed" stance makes it easier to swing the club from the inside, promoting a draw. Hit 10 drives.',
    scoringMethodology: 'Focus on ball flight. 3 points for a draw, 1 point for straight, 0 for a slice.',
    icon: 'Footprints',
    targetsAreaOfPotential: ['drivingSlice', 'consistentMissRight'],
    maxScore: 30,
  },
  {
    id: 'd68',
    name: 'One-Armed Swings',
    category: 'Driving',
    difficulty: 'Beginner',
    description: 'Take 5 easy, half-speed swings using only your lead arm (left arm for right-handers). Then 5 swings with only your trail arm. This helps feel the role of each arm in the swing and improves sequencing. Do not use a ball.',
    scoringMethodology: 'No score. This is purely for feel and mechanics. Use notes to describe what you felt.',
    icon: 'Hand',
    targetsAreaOfPotential: ['swingMechanics', 'tempo'],
    maxScore: 0,
  },
  {
    id: 'd69',
    name: 'Driver Off a Short Tee',
    category: 'Driving',
    difficulty: 'Advanced',
    description: 'Practice hitting your driver off a very short tee, similar to what you\'d use for an iron. This forces you to be very precise with your angle of attack and strike, promoting a lower, more controlled "stinger" type of shot for tight or windy conditions. Hit 10 shots.',
    scoringMethodology: 'Score out of 10 based on the quality of strike and low, penetrating trajectory.',
    icon: 'ArrowDownToLine',
    targetsAreaOfPotential: ['shotShaping', 'drivingAccuracyGeneral'],
    maxScore: 10,
  },
  {
    id: 'd70',
    name: 'Stock Yardage Dial-In',
    category: 'Approach',
    difficulty: 'Beginner',
    description: 'Take your 7-iron. Hit 10 shots, trying to make the same smooth, repeatable swing each time. Use a rangefinder to measure the carry distance of each shot. The goal is to find your true, average carry distance, not your absolute best.',
    scoringMethodology: 'No score. Record all 10 carry distances in your notes and calculate your average and range (e.g., 155 avg, range 151-159).',
    icon: 'Ruler',
    targetsAreaOfPotential: ['approachDistanceControl', 'approachConsistency'],
    maxScore: 0,
  },
  {
    id: 'd71',
    name: 'Worst-Ball Scramble (Solo)',
    category: 'Approach',
    difficulty: 'Advanced',
    description: 'From 150 yards, hit two balls. Pick the worse of the two shots, and hit your next two shots from that spot. Continue until you hole out. This drill adds pressure and forces you to recover from a bad shot. Play 3 "holes" like this.',
    scoringMethodology: 'Record your total score for the 3 holes. The goal is to keep the score as low as possible.',
    icon: 'Recycle',
    targetsAreaOfPotential: ['approachConsistency', 'courseManagement', 'mentalGame'],
    maxScore: 0,
  },
  {
    id: 'd72',
    name: 'Specific Quadrant Challenge',
    category: 'Approach',
    difficulty: 'Intermediate',
    description: 'Mentally divide a practice green into four quadrants (front-left, front-right, back-left, back-right). From 120 yards, hit 3 shots into each quadrant. This drill is more precise than simply aiming for the green.',
    scoringMethodology: 'Score 1 point for each shot that lands in the correct quadrant. Max score of 12.',
    icon: 'AppWindow',
    targetsAreaOfPotential: ['girLow', 'approachAccuracy', 'shotShaping'],
    maxScore: 12,
  },
  {
    id: 'd73',
    name: 'Impact Sound & Feel',
    category: 'Approach',
    difficulty: 'Beginner',
    description: 'Using a mid-iron, hit 10 shots focusing only on the quality of the strike. Ignore the result. Try to achieve a "compressed" feel and a solid "thump-click" sound. Rate each shot\'s feel out of 5 in your notes.',
    scoringMethodology: 'No score. This is purely about developing better ball-striking feel.',
    icon: 'Ear',
    targetsAreaOfPotential: ['ballStriking', 'approachConsistency'],
    maxScore: 0,
  },
  {
    id: 'd74',
    name: 'The 30-Yard "In-Between" Shot',
    category: 'Approach',
    difficulty: 'Intermediate',
    description: 'Many golfers struggle with awkward 30-40 yard pitch shots. Drop 10 balls at this distance and practice hitting them to a flag. Experiment with different clubs (e.g., a sand wedge vs. a gap wedge) and swing lengths.',
    scoringMethodology: 'Award points based on final proximity to the pin for the 10 shots.',
    icon: 'HelpCircle',
    targetsAreaOfPotential: ['approachDistanceControl', 'shortGameScrambling'],
    maxScore: 0,
  },
  {
    id: 'd75',
    name: 'Flyer Lie Practice',
    category: 'Approach',
    difficulty: 'Advanced',
    description: 'Find some light to medium rough. Drop 10 balls. Hit shots to a green from about 100-120 yards out. Try to predict how much the ball will "jump" or "fly" from the rough with reduced spin.',
    scoringMethodology: 'No score. Use notes to record the difference in carry distance compared to a fairway shot.',
    icon: 'Rocket',
    targetsAreaOfPotential: ['courseManagement', 'approachDistanceControl'],
    maxScore: 0,
  },
  {
    id: 'd76',
    name: 'Greenside Bunker Approach',
    category: 'Approach',
    difficulty: 'Intermediate',
    description: 'This drill is about avoiding trouble. The target is a green with a large bunker guarding one side. Hit 10 approach shots with the explicit goal of finishing anywhere on the green except in that bunker.',
    scoringMethodology: '1 point for every shot that avoids the bunker and lands on the green. 0 points if you end up in the bunker.',
    icon: 'ShieldAlert',
    targetsAreaOfPotential: ['courseManagement', 'girLow'],
    maxScore: 10,
  },
  {
    id: 'd77',
    name: 'Quick-Fire Routine',
    category: 'Approach',
    difficulty: 'Intermediate',
    description: 'This drill is for pace of play and decisiveness. Once you know the yardage, give yourself 15 seconds to select a club, get set, and hit the shot. Hit 10 shots this way.',
    scoringMethodology: 'Score 1 point for each shot executed within the 15-second time limit.',
    icon: 'FastForward',
    targetsAreaOfPotential: ['preShotRoutine', 'mentalGame'],
    maxScore: 10,
  },
  {
    id: 'd78',
    name: 'Punch Shot Low Trajectory',
    category: 'Approach',
    difficulty: 'Intermediate',
    description: 'Practice hitting low, controlled "punch" shots. Play the ball further back in your stance, put more weight on your front foot, and make an abbreviated follow-through. This is crucial for hitting under trees or in the wind. Hit 10 shots to a 100-yard target.',
    scoringMethodology: 'Score based on successfully keeping the trajectory below a certain imaginary line (e.g., a tree branch).',
    icon: 'ArrowDownToLine',
    targetsAreaOfPotential: ['shotShaping', 'courseManagement'],
    maxScore: 10,
  },
  {
    id: 'd79',
    name: '"Par 3" Simulation',
    category: 'Approach',
    difficulty: 'Beginner',
    description: 'On the range, find yardage markers for typical par 3 distances (e.g., 130, 150, 170 yards). Hit 3 shots to each "green," going through your full routine each time.',
    scoringMethodology: 'Score 1 point for each shot that you feel would have landed on the green.',
    icon: 'Flag',
    targetsAreaOfPotential: ['girLow', 'approachConsistency'],
    maxScore: 9,
  },
  {
    id: 'd80',
    name: 'Three-Quarter Swing Control',
    category: 'Approach',
    difficulty: 'Beginner',
    description: 'Take your 9-iron. Hit 10 shots using a smooth, controlled three-quarter backswing and follow-through. Note the distance. This is often more consistent than a full swing and is a vital "go-to" shot under pressure.',
    scoringMethodology: 'No score. The goal is to learn the distance and feel of a reliable, controlled swing.',
    icon: 'Gauge',
    targetsAreaOfPotential: ['approachDistanceControl', 'tempo'],
    maxScore: 0,
  },
  {
    id: 'd81',
    name: 'Landing on a Slope',
    category: 'Around the Green',
    difficulty: 'Intermediate',
    description: 'Find a practice green with a significant slope. From off the green, practice landing your chip on the slope and predicting how the ball will break and release towards the hole. Hit 10 shots.',
    scoringMethodology: 'Score based on final proximity to the hole.',
    icon: 'Mountain',
    targetsAreaOfPotential: ['shortGameScrambling', 'greenReading', 'upAndDownLow'],
    maxScore: 0,
  },
  {
    id: 'd82',
    name: 'Bare/Tight Lie Chipping',
    category: 'Around the Green',
    difficulty: 'Advanced',
    description: 'Find a very short, firm area of grass or even a bare lie on the practice area. Practice chipping from this lie. It requires very precise contact. Use less wrist action and a more "putting-style" stroke. Hit 10 chips.',
    scoringMethodology: 'Score out of 10 based on the quality of the strike (avoiding thin or fat shots).',
    icon: 'CircleSlash',
    targetsAreaOfPotential: ['shortGameScrambling', 'ballStriking'],
    maxScore: 10,
  },
  {
    id: 'd83',
    name: 'Pitching from Deep Rough',
    category: 'Around the Green',
    difficulty: 'Intermediate',
    description: 'From 10-15 yards away, drop 10 balls in the thickest rough you can find. Practice pitching out of this lie. This requires a steeper downswing and accelerating through the ball to prevent the club from getting stuck.',
    scoringMethodology: '3 points: On the green within 10ft. 1 point: On the green. 0 points: Off the green.',
    icon: 'Waves',
    targetsAreaOfPotential: ['shortGameScrambling', 'toughLies'],
    maxScore: 30,
  },
  {
    id: 'd84',
    name: 'The "One-Hop-and-Stop" Pitch',
    category: 'Around the Green',
    difficulty: 'Advanced',
    description: 'From 20-30 yards, practice hitting a high, soft pitch shot with lots of spin that lands, takes one significant bounce, and stops quickly. This requires a high-lofted wedge, an open clubface, and speed through impact. Hit 10 shots.',
    scoringMethodology: 'Score 1 point for each shot that successfully performs the "one hop and stop".',
    icon: 'Locate',
    targetsAreaOfPotential: ['shotShaping', 'shortGameScrambling'],
    maxScore: 10,
  },
  {
    id: 'd85',
    name: 'Buried Bunker Lie',
    category: 'Around the Green',
    difficulty: 'Advanced',
    description: 'In a practice bunker, step on your ball to create a "fried egg" or buried lie. To get it out, square the clubface (don\'t open it), and use a very steep, powerful downswing right behind the ball. Hit 10 shots.',
    scoringMethodology: '1 point for successfully escaping the sand and landing on the green.',
    icon: 'ArrowDownToLine',
    targetsAreaOfPotential: ['sandSavesLow', 'shortGameBunker', 'toughLies'],
    maxScore: 10,
  },
  {
    id: 'd86',
    name: 'Long Chip/Pitch',
    category: 'Around the Green',
    difficulty: 'Intermediate',
    description: 'Practice chipping and pitching from 30-40 yards away from the green. This is often an awkward "in-between" distance. Find a club and swing length that feels comfortable and produces a consistent result. Hit 10 shots.',
    scoringMethodology: 'Score based on proximity to the hole.',
    icon: 'StretchHorizontal',
    targetsAreaOfPotential: ['distanceControl', 'shortGameScrambling', 'upAndDownLow'],
    maxScore: 0,
  },
  {
    id: 'd87',
    name: 'Chipping "Race to 21"',
    category: 'Around the Green',
    difficulty: 'Intermediate',
    description: 'From a single spot, chip balls to a hole. Score 5 points if you hole it, 3 points if within 3ft, 1 point if within 6ft. The first player (or you against yourself) to reach 21 points wins the game.',
    scoringMethodology: 'How many shots did it take you to reach 21 points?',
    icon: 'Trophy',
    targetsAreaOfPotential: ['shortGameScrambling', 'upAndDownLow', 'puttingUnderPressure'],
    maxScore: 0,
  },
  {
    id: 'd88',
    name: 'Creating a Landing Spot "Box"',
    category: 'Around the Green',
    difficulty: 'Beginner',
    description: 'Use four tees to create a 2ft by 2ft box on the green where you want your chip to land. From 10 yards off the green, hit 10 shots trying to land the ball inside the box.',
    scoringMethodology: 'Count how many shots land inside the box.',
    icon: 'Container',
    targetsAreaOfPotential: ['upAndDownLow', 'distanceControl'],
    maxScore: 10,
  },
  {
    id: 'd89',
    name: 'Fairway Bunker Approach',
    category: 'Around the Green',
    difficulty: 'Advanced',
    description: 'Practice approach shots from a fairway bunker (if your facility has one). The key is a clean strike, so choke down on the club and make a smooth, balanced swing. Hit 10 shots towards a green 100-150 yards away.',
    scoringMethodology: 'Score out of 10 for clean contact and good distance. Landing on the green is a bonus.',
    icon: 'Send',
    targetsAreaOfPotential: ['courseManagement', 'approachConsistency', 'toughLies'],
    maxScore: 10,
  },
  {
    id: 'd90',
    name: 'Chipping with Your Eyes Closed',
    category: 'Around the Green',
    difficulty: 'Advanced',
    description: 'From a simple 10-yard chipping spot, set up to the ball, have one last look at the hole, and then close your eyes for your stroke. This drill builds immense trust in your setup and stroke mechanics.',
    scoringMethodology: 'No score. Use notes to describe the quality of contact and your ability to commit to the shot.',
    icon: 'EyeOff',
    targetsAreaOfPotential: ['shortGameScrambling', 'feel'],
    maxScore: 0,
  },
  {
    id: 'd91',
    name: 'The Metronome Tempo Drill',
    category: 'Putting',
    difficulty: 'Beginner',
    description: 'Use a metronome app on your phone (set to around 70-80 bpm). Let one beat be the top of your backstroke and the next beat be impact. Hit 10 putts from 10 feet, trying to match your stroke tempo perfectly to the metronome.',
    scoringMethodology: 'No score. Focus on creating a smooth, repeatable tempo.',
    icon: 'GaugeCircle',
    targetsAreaOfPotential: ['puttingConsistencyGeneral', 'tempo'],
    maxScore: 0,
  },
  {
    id: 'd92',
    name: 'Breaking Putt Line & Speed',
    category: 'Putting',
    difficulty: 'Intermediate',
    description: 'Find a 10-foot putt with a significant break. Place a tee at the apex of the break. Your goal is to roll the ball over the tee with the right speed for it to curve into the hole. Hit 10 putts.',
    scoringMethodology: '3 points: Putt holed. 1 point: Ball rolls over the tee but misses. 0 points: Ball misses the tee.',
    icon: 'Spline',
    targetsAreaOfPotential: ['greenReading', 'putting10ftLowPercentage'],
    maxScore: 30,
  },
  {
    id: 'd93',
    name: 'Coin Drill for Solid Strike',
    category: 'Putting',
    difficulty: 'Beginner',
    description: 'Place a small coin on the green. Practice making putting strokes where your putter just brushes the top of the coin without moving it. Then, place a ball on the coin and repeat, focusing on a slightly upward strike.',
    scoringMethodology: 'Process-based. This drill is for improving the quality of your putting strike.',
    icon: 'CircleDollarSign',
    targetsAreaOfPotential: ['puttingConsistencyGeneral', 'ballStriking'],
    maxScore: 0,
  },
  {
    id: 'd94',
    name: '"Must Make" 3-Footers',
    category: 'Putting',
    difficulty: 'Beginner',
    description: 'Place 10 balls in a line, each 3 feet from the hole. You cannot leave the practice green until you have holed all 10 in a row. If you miss, you must start the count again from zero.',
    scoringMethodology: 'Record how many attempts it took to make 10 in a row.',
    icon: 'Lock',
    targetsAreaOfPotential: ['putting5ftLowPercentage', 'puttingUnderPressure'],
    maxScore: 0,
  },
  {
    id: 'd95',
    name: 'The String Line Path Drill',
    category: 'Putting',
    difficulty: 'Intermediate',
    description: 'Set up a 6-foot straight putt. Tie a string between two stakes, running directly over the ball-to-hole line, a few inches above the ground. Practice making strokes where your putter head moves straight back and straight through underneath the string.',
    scoringMethodology: 'This is a mechanical drill. No score, but note your consistency.',
    icon: 'RailSymbol',
    targetsAreaOfPotential: ['puttingConsistencyGeneral', 'putting5ftLowPercentage'],
    maxScore: 0,
  },
  {
    id: 'd96',
    name: 'Backboard Putting',
    category: 'Putting',
    difficulty: 'Beginner',
    description: 'Place a book or a board a foot behind the hole. Hit 10-foot putts with enough pace to reach the hole, but not so much that they would hit the backboard hard if they missed. This refines your speed on makeable putts.',
    scoringMethodology: 'Score 1 point for every putt holed or that gently touches the backboard.',
    icon: 'PanelBottom',
    targetsAreaOfPotential: ['puttingDistanceControl', 'putting10ftLowPercentage'],
    maxScore: 10,
  },
  {
    id: 'd97',
    name: 'Look at the Hole, Not the Ball',
    category: 'Putting',
    difficulty: 'Intermediate',
    description: 'On 10-20 foot putts, set up as normal but keep your eyes focused on the hole throughout the entire putting stroke. Do not look at the ball. This can improve feel for distance and free up a tense stroke. Hit 10 putts.',
    scoringMethodology: 'No score. Use notes to describe how this drill impacted your distance control and confidence.',
    icon: 'Eye',
    targetsAreaOfPotential: ['puttingDistanceControl', 'feel'],
    maxScore: 0,
  },
  {
    id: 'd98',
    name: 'Putt from Another Hole\'s Fringe',
    category: 'Putting',
    difficulty: 'Intermediate',
    description: 'On a large practice green, putt from the fringe of one hole to another hole 20+ yards away. This is an extreme lag putting drill that forces you to be creative and dial in your feel for speed. Hit 5 monster putts.',
    scoringMethodology: 'Measure the final proximity of each putt to the hole.',
    icon: 'MoveDiagonal',
    targetsAreaOfPotential: ['putting21plusYardsLowPercentage', 'puttingDistanceControl'],
    maxScore: 0,
  },
  {
    id: 'd99',
    name: '"Finish the Drill" Putting',
    category: 'Putting',
    difficulty: 'Beginner',
    description: 'After completing any chipping or pitching drill, you must hole out every putt, no matter how close or far. Do not just rake the balls away. This builds the habit of finishing and adds pressure to your short game practice.',
    scoringMethodology: 'Count the total number of putts it takes to hole out all the balls from your previous drill.',
    icon: 'CheckCheck',
    targetsAreaOfPotential: ['puttingUnderPressure', 'upAndDownLow'],
    maxScore: 0,
  },
  {
    id: 'd100',
    name: 'The 10-Putt Challenge',
    category: 'Putting',
    difficulty: 'Intermediate',
    description: 'Drop 10 balls randomly around a hole, at various distances between 5 and 25 feet. Play each one as if it were in a real round. The goal is to complete all 10 putts in as few total strokes as possible.',
    scoringMethodology: 'Record your total strokes for the 10 "holes". Aim for under 18 strokes.',
    icon: 'Puzzle',
    targetsAreaOfPotential: ['puttingConsistencyGeneral', 'threePuttHigh'],
    maxScore: 0,
  },
  {
    id: 'd101',
    name: 'Tee for Iron Strike',
    category: 'General Setup',
    difficulty: 'Beginner',
    description: 'On the range, place your iron shots on a very short tee. This encourages a sweeping motion and helps you find the low point of your swing, improving contact. Hit 10 shots.',
    scoringMethodology: 'Score out of 10 for shots that felt "flushed" off the tee.',
    icon: 'Pin',
    targetsAreaOfPotential: ['ballStriking', 'approachConsistency'],
    maxScore: 10,
  },
  {
    id: 'd102',
    name: '"Feel vs. Real" Swing Check',
    category: 'General Setup',
    difficulty: 'Intermediate',
    description: 'Make a practice swing where you feel a certain move (e.g., "shorter backswing"). Then, record yourself hitting a ball with that same feeling. Compare the video (the "real") to your intended feeling. Repeat for 5 different feelings.',
    scoringMethodology: 'No score. Use notes to document the difference between your feel and the reality on video.',
    icon: 'Camera',
    targetsAreaOfPotential: ['swingMechanics', 'feel'],
    maxScore: 0,
  },
  {
    id: 'd103',
    name: 'Step-Through Drill',
    category: 'General Setup',
    difficulty: 'Intermediate',
    description: 'Make a normal golf swing with a mid-iron. Immediately after impact, let your back foot step through towards the target, walking after the shot. This encourages proper weight transfer and sequence. Hit 10 shots.',
    scoringMethodology: 'Score out of 10 for shots where you maintained balance throughout the step-through motion.',
    icon: 'MoveRight',
    targetsAreaOfPotential: ['balance', 'swingMechanics', 'tempo'],
    maxScore: 10,
  },
  {
    id: 'd104',
    name: 'Club Parallel Check',
    category: 'General Setup',
    difficulty: 'Beginner',
    description: 'At the top of your backswing, pause and check if the club is parallel to the ground and parallel to your target line. Use a mirror or phone video to verify. Make 10 practice swings, pausing at the top of each.',
    scoringMethodology: 'Score 1 point for each swing that reaches the correct position.',
    icon: 'MoveHorizontal',
    targetsAreaOfPotential: ['swingMechanics', 'drivingAccuracyGeneral'],
    maxScore: 10,
  },
  {
    id: 'd105',
    name: 'The Towel Drill (Chicken Wing Fix)',
    category: 'General Setup',
    difficulty: 'Intermediate',
    description: 'Place a small towel under your lead arm\'s armpit (left arm for right-handers). Hit 10 half-swing shots with a short iron, trying to keep the towel from falling out until after impact. This promotes keeping your arms and body connected.',
    scoringMethodology: 'No score. Focus on the feeling of connection.',
    icon: 'FileBadge',
    targetsAreaOfPotential: ['swingMechanics', 'ballStriking'],
    maxScore: 0,
  },
  {
    id: 'd106',
    name: 'One-Piece Takeaway',
    category: 'General Setup',
    difficulty: 'Beginner',
    description: 'At address, feel your arms, shoulders, and chest form a triangle. For the first few feet of your backswing, move this triangle back as a single unit without breaking your wrists. Place a headcover under both armpits to help. Make 10 practice swings.',
    scoringMethodology: 'Score yourself on your ability to maintain the "one-piece" feel for the first part of the swing.',
    icon: 'Triangle',
    targetsAreaOfPotential: ['swingMechanics', 'tempo'],
    maxScore: 10,
  },
  {
    id: 'd107',
    name: 'Quiet Head Drill',
    category: 'General Setup',
    difficulty: 'Intermediate',
    description: 'Hit 10 shots while trying to keep your head as still as possible from address through impact. Imagine your head is against a wall. This stabilises your swing axis and improves consistency of strike.',
    scoringMethodology: 'Score out of 10 for shots where you felt your head remained stable.',
    icon: 'Anchor',
    targetsAreaOfPotential: ['swingMechanics', 'ballStriking'],
    maxScore: 10,
  },
  {
    id: 'd108',
    name: 'The "Whoosh" Drill',
    category: 'General Setup',
    difficulty: 'Beginner',
    description: 'Turn a mid-iron upside down and hold it by the clubhead. Make 10 full, fast swings. Listen for the "whoosh" sound. The "whoosh" should be at its loudest after where the ball would be, in the impact and follow-through zone, not on the downswing.',
    scoringMethodology: 'No score. This drill is for training speed and proper release point.',
    icon: 'AudioWaveform',
    targetsAreaOfPotential: ['tempo', 'swingMechanics'],
    maxScore: 0,
  },
  {
    id: 'd109',
    name: 'Feet Together Drill',
    category: 'General Setup',
    difficulty: 'Intermediate',
    description: 'Hit 10 shots with a short iron with your feet completely together. This will feel strange, but it forces you to rely on body rotation and arm swing rather than swaying, dramatically improving balance.',
    scoringMethodology: 'Score out of 10 for maintaining balance and making a clean strike.',
    icon: 'Combine',
    targetsAreaOfPotential: ['balance', 'swingMechanics', 'tempo'],
    maxScore: 10,
  },
  {
    id: 'd110',
    name: '"Play the Course" on the Range',
    category: 'General Setup',
    difficulty: 'Intermediate',
    description: 'Visualise playing the first 3 holes of your home course. Hit the driver for the first tee shot, then the appropriate iron for the approach, then a chip if you "missed". Change clubs for every shot as you would in a real round.',
    scoringMethodology: 'No score. The goal is to make practice more challenging and realistic.',
    icon: 'Map',
    targetsAreaOfPotential: ['courseManagement', 'focus', 'preShotRoutine'],
    maxScore: 0,
  },
  {
    id: 'm1',
    name: 'Visualization: Perfect Shot',
    category: 'Mental Game',
    difficulty: 'Beginner',
    description: 'Before a practice shot, close your eyes and vividly imagine executing the perfect shot. See the ball flight, feel the perfect swing, and picture the ideal outcome. Do this for 10 shots.',
    scoringMethodology: 'Process-based. Score 1 point for each shot where you successfully visualized the outcome before hitting. Note any impact on your actual shot.',
    icon: 'Brain',
    targetsAreaOfPotential: ['mentalGame', 'visualization', 'focus', 'preShotRoutine', 'confidence'],
    maxScore: 10,
  },
  {
    id: 'm2',
    name: 'Box Breathing for Pressure Shots',
    category: 'Mental Game',
    difficulty: 'Beginner',
    description: 'Before a challenging practice putt or tee shot, perform "box breathing". Inhale for a count of 4, hold for 4, exhale for 4, hold for 4. Repeat 3-5 times to lower your heart rate and calm your nerves.',
    scoringMethodology: 'No score. Use the notes section to record how your body and mind felt after the breathing exercise compared to before.',
    icon: 'HeartPulse',
    targetsAreaOfPotential: ['mentalGame', 'puttingUnderPressure', 'tempo'],
    maxScore: 0,
  },
  {
    id: 'm3',
    name: 'One-Thought Swing',
    category: 'Mental Game',
    difficulty: 'Intermediate',
    description: 'For 10 range shots, your only goal is to have a single, positive swing thought (e.g., "smooth tempo" or "hold the finish"). Actively block out all other technical thoughts. This drill helps to quiet a busy mind over the ball.',
    scoringMethodology: 'Score 1 point for each shot where you successfully maintained only one swing thought. 0 if your mind cluttered with other thoughts.',
    icon: 'Brain',
    targetsAreaOfPotential: ['mentalGame', 'focus', 'preShotRoutine'],
    maxScore: 10,
  },
  {
    id: 'm4',
    name: 'Session 1: The 10-Second Rule: Mastering Your Post-Shot Reaction',
    category: 'Mental Game',
    difficulty: 'Intermediate',
    description: 'Hit 10 shots. After each shot, good or bad, give yourself a maximum of 10 seconds to react (positively or negatively). After 10 seconds, turn away and focus on the next shot, leaving the previous one behind. This builds resilience.',
    scoringMethodology: 'Process-based. Score yourself out of 10 on your ability to "reset" after the 10-second window.',
    icon: 'Brain',
    targetsAreaOfPotential: ['mentalGame', 'courseManagement'],
    audioUrl: '/images/audio/Session 1 - Mental approach - The 10 second rule.wav',
    maxScore: 10,
  },
  {
    id: 'm5',
    name: '"Forget the Last Shot" Drill',
    category: 'Mental Game',
    difficulty: 'Advanced',
    description: 'On the range, hit what you consider a "bad" shot deliberately (e.g., a big slice). Then, immediately step up to a second ball and hit it, going through your full routine as if the bad shot never happened. Repeat this 5 times.',
    scoringMethodology: 'Score your "recovery" shot on a scale of 1-3. The goal is to not let one bad shot bleed into the next.',
    icon: 'Undo2',
    targetsAreaOfPotential: ['mentalGame', 'resilience'],
    maxScore: 15,
  },
  {
    id: 'm6',
    name: 'Strategic Decision Making',
    category: 'Mental Game',
    difficulty: 'Intermediate',
    description: 'Before a practice shot, state your strategy out loud. For example: "The pin is tucked right, so I will aim for the centre of the green and let the ball feed towards the hole." Verbalizing your strategy reinforces smart decisions. Do this for 10 approach shots.',
    scoringMethodology: 'Score 1 point for each shot where you stated a clear strategy and committed to it.',
    icon: 'Map',
    targetsAreaOfPotential: ['courseManagement', 'focus', 'mentalGame'],
    maxScore: 10,
  },
  {
    id: 'm7',
    name: 'Gratitude Walk',
    category: 'Mental Game',
    difficulty: 'Beginner',
    description: 'During a practice round or even on the range, take a moment between shots to identify one thing you enjoy about playing golf (e.g., being outdoors, the feeling of a good strike, spending time alone). This helps maintain perspective and enjoyment.',
    scoringMethodology: 'No score. The goal is to reduce frustration and increase enjoyment. Use the notes section for your thoughts.',
    icon: 'Smile',
    targetsAreaOfPotential: ['mentalGame', 'enjoyment'],
    maxScore: 0,
  },
  {
    id: 'm8',
    name: 'Commitment Drill',
    category: 'Mental Game',
    difficulty: 'Intermediate',
    description: 'Before each of 10 shots, rate your commitment to your chosen club and shot shape on a scale of 1-5. After the shot, reflect on whether your commitment level matched the quality of the result. This drill highlights indecision.',
    scoringMethodology: 'No score. This is for self-assessment. Use notes to track your commitment ratings.',
    icon: 'ClipboardList',
    targetsAreaOfPotential: ['mentalGame', 'preShotRoutine', 'focus'],
    maxScore: 0,
  },
  {
    id: 'm9',
    name: 'Body Tension Scan',
    category: 'Mental Game',
    difficulty: 'Beginner',
    description: 'Before your swing, close your eyes and mentally scan your body for tension. Start with your hands (grip pressure), then move to your arms, shoulders, neck, and jaw. Consciously release any tension you find. Repeat for 10 shots.',
    scoringMethodology: 'Process-based. Score yourself out of 10 on your ability to identify and release tension before swinging.',
    icon: 'ScanLine',
    targetsAreaOfPotential: ['mentalGame', 'tempo', 'setupConsistency'],
    maxScore: 10,
  },
  {
    id: 'm10',
    name: '"Play to Your Strengths" Simulation',
    category: 'Mental Game',
    difficulty: 'Advanced',
    description: 'Visualize a hole you find difficult. Instead of planning the "perfect" shot, plan to play the hole using only your most reliable, "go-to" shots, even if it means not hitting driver or aiming away from the flag. This builds course management skills.',
    scoringMethodology: 'No score. Use notes to describe your strategic plan for the hole. Compare it to how you usually play it.',
    icon: 'Brain',
    targetsAreaOfPotential: ['courseManagement', 'mentalGame', 'confidence'],
    maxScore: 0,
  },
  {
    id: 'm11',
    name: 'Session 2: Building Your "Confidence Bank"',
    category: 'Mental Game',
    difficulty: 'Beginner',
    description: 'Discover how confidence is a trainable skill, not a random feeling. This session teaches you how to build a mental library of your best shots to draw upon when you need it most.',
    scoringMethodology: 'No score. This session is for reflection and building a mental tool. Use notes to document your positive shot memories.',
    icon: 'Brain',
    targetsAreaOfPotential: ['mentalGame', 'confidence', 'visualization'],
    audioUrl: '/images/audio/Session 2 - Mental approach - Building a confidence bank.wav',
    maxScore: 0,
  },
  {
    id: 'm12',
    name: 'Session 3: The Process Mindset: Separating Your Swing from Your Score',
    category: 'Mental Game',
    difficulty: 'Intermediate',
    description: 'Shift your focus from uncontrollable outcomes to the controllable actions you take before every swing. Learn why trusting your process is the most reliable path to lower scores.',
    scoringMethodology: 'No score. This session is about understanding a concept. Use notes to reflect on how you can apply a process mindset to your game.',
    icon: 'Brain',
    targetsAreaOfPotential: ['mentalGame', 'focus', 'preShotRoutine', 'resilience'],
    audioUrl: '/images/audio/Session 3 - The process mindset .wav',
    maxScore: 0,
  },
  {
    id: 'm13',
    name: 'Session 4: One Shot at a Time: The Art of Staying Present',
    category: 'Mental Game',
    difficulty: 'Intermediate',
    description: "We all walk the fairway in a literal sense, but what if e could walk the 'Mental Fairway' from the last shot to the next to maintain our focus and resilience? In this session we look at how we can do just that.",
    scoringMethodology: 'No score. This session is about learning a mental technique to use on the course.',
    icon: 'Brain',
    targetsAreaOfPotential: ['mentalGame', 'focus', 'resilience', 'courseManagement'],
    audioUrl: '/images/audio/Session 4 - One Shot at a Time - The Art of Staying Present.wav',
    maxScore: 0,
  },
  {
    id: 'm14',
    name: 'Session 5: First Tee Nerves: Turning Fear into Focus',
    category: 'Mental Game',
    difficulty: 'Intermediate',
    description: 'We have all heard of \'Fight vs Flight\'. Golf is never that serious but we do all feel nerves and here we look at how best to channel them.',
    scoringMethodology: 'No score. This session is about learning a mental technique to use on the course.',
    icon: 'Brain',
    targetsAreaOfPotential: ['mentalGame', 'puttingUnderPressure', 'preShotRoutine', 'focus'],
    audioUrl: '/images/audio/Session 5 - First Tee Nerves - Turning Fear into Focus.wav',
    maxScore: 0,
  },
  {
    id: 'm15',
    name: 'Session 6: The Power of Golf Visualisation',
    category: 'Mental Game',
    difficulty: 'Intermediate',
    description: "The core principle of this session is that visualisation is one of the most powerful mental tools a golfer can possess. Let's make sure you start developing it too!",
    scoringMethodology: 'No score. This session is about learning a mental technique to use on the course.',
    icon: 'Brain',
    targetsAreaOfPotential: ['mentalGame', 'visualization', 'focus', 'confidence'],
    audioUrl: '/images/audio/Session 6 - The Power of Golf Visualisation.wav',
    maxScore: 0,
  }
];

export const imageUrls = {
  morning: 'https://placehold.co/1920x1080.png',
  midday: '/images/midday.jpg',
  evening: '/images/evening.jpg'
};

export const initialAchievements: Achievement[] = [
  // Onboarding & Setup
  {
    id: 'ach_first_round',
    name: 'My First Round!',
    description: 'Log your very first round of golf in the app.',
    icon: 'Flag',
    isUnlocked: (data: AchievementData) => data.rounds.length > 0,
    progress: (data: AchievementData) => ({ current: Math.min(data.rounds.length, 1), target: 1, unit: 'round' }),
    getInstances: (data: AchievementData) => {
        return data.rounds
            .slice(0, 1)
            .map(r => ({
                date: format(new Date(r.roundDate), 'PP'),
                description: `First round logged at ${r.courseName} with a score of ${r.grossScore}.`
            }));
    }
  },
  {
    id: 'ach_profile_complete',
    name: 'Profile Pro',
    description: 'Complete your profile by setting a custom display name and your handicap.',
    icon: 'UserCircle',
    isUnlocked: (data: AchievementData) => {
      if (!data.profile || !data.profile.email) return false;
      const hasHandicap = !!data.profile.handicap;
      const defaultName1 = data.profile.email.split('@')[0];
      const defaultName2 = 'New User';
      const hasCustomDisplayName = !!data.profile.displayName && data.profile.displayName !== defaultName1 && data.profile.displayName !== defaultName2;
      return hasHandicap && hasCustomDisplayName;
    },
    progress: (data: AchievementData) => {
      if (!data.profile || !data.profile.email) return { current: 0, target: 2, unit: 'fields' };
      const hasHandicap = !!data.profile.handicap;
      const defaultName1 = data.profile.email.split('@')[0];
      const defaultName2 = 'New User';
      const hasCustomDisplayName = !!data.profile.displayName && data.profile.displayName !== defaultName1 && data.profile.displayName !== defaultName2;
      return { current: (hasHandicap ? 1 : 0) + (hasCustomDisplayName ? 1 : 0), target: 2, unit: 'fields' };
    },
  },
  {
    id: 'ach_top_fan',
    name: 'Top Fan',
    description: 'Mark 3 drills as your favourites.',
    icon: 'Star',
    isUnlocked: (data: AchievementData) => data.favouriteDrillIds.length >= 3,
    progress: (data: AchievementData) => ({ current: data.favouriteDrillIds.length, target: 3, unit: 'drills' }),
  },
  // Performance Milestones
  {
    id: 'ach_century_breaker',
    name: 'Century Breaker',
    description: 'Break 100 in an on-course round.',
    icon: 'TrendingUp',
    isUnlocked: (data: AchievementData) => data.rounds.some(r => r.roundType !== 'Indoor' && parseInt(r.grossScore) < 100),
    getInstances: (data: AchievementData) => {
        return data.rounds
            .filter(r => r.roundType !== 'Indoor' && parseInt(r.grossScore) < 100)
            .sort((a, b) => new Date(b.roundDate).getTime() - new Date(a.roundDate).getTime())
            .slice(0, 5)
            .map(r => ({
                date: format(new Date(r.roundDate), 'PP'),
                description: `Shot ${r.grossScore} at ${r.courseName}.`
            }));
    }
  },
  {
    id: 'ach_bogey_golfer',
    name: 'Bogey Golfer',
    description: 'Break 90 in an on-course round.',
    icon: 'TrendingUp',
    isUnlocked: (data: AchievementData) => data.rounds.some(r => r.roundType !== 'Indoor' && parseInt(r.grossScore) < 90),
    getInstances: (data: AchievementData) => {
        return data.rounds
            .filter(r => r.roundType !== 'Indoor' && parseInt(r.grossScore) < 90)
            .sort((a, b) => new Date(b.roundDate).getTime() - new Date(a.roundDate).getTime())
            .slice(0, 5)
            .map(r => ({
                date: format(new Date(r.roundDate), 'PP'),
                description: `Shot ${r.grossScore} at ${r.courseName}.`
            }));
    }
  },
  {
    id: 'ach_birdie_machine',
    name: 'Birdie Machine',
    description: 'Break 80 in an on-course round.',
    icon: 'TrendingUp',
    isUnlocked: (data: AchievementData) => data.rounds.some(r => r.roundType !== 'Indoor' && parseInt(r.grossScore) < 80),
     getInstances: (data: AchievementData) => {
        return data.rounds
            .filter(r => r.roundType !== 'Indoor' && parseInt(r.grossScore) < 80)
            .sort((a, b) => new Date(b.roundDate).getTime() - new Date(a.roundDate).getTime())
            .slice(0, 5)
            .map(r => ({
                date: format(new Date(r.roundDate), 'PP'),
                description: `Shot ${r.grossScore} at ${r.courseName}.`
            }));
    }
  },
  {
    id: 'ach_par_breaker',
    name: 'Par Breaker',
    description: 'Log an on-course round of even par or better.',
    icon: 'Target',
    isUnlocked: (data: AchievementData) => data.rounds.some(r => r.roundType !== 'Indoor' && parseScoreToPar(r.scoreToPar) <= 0),
     getInstances: (data: AchievementData) => {
        return data.rounds
            .filter(r => r.roundType !== 'Indoor' && parseScoreToPar(r.scoreToPar) <= 0)
            .sort((a, b) => new Date(b.roundDate).getTime() - new Date(a.roundDate).getTime())
            .slice(0, 5)
            .map(r => ({
                date: format(new Date(r.roundDate), 'PP'),
                description: `Shot ${r.grossScore} (${r.scoreToPar}) at ${r.courseName}.`
            }));
    }
  },
  {
    id: 'ach_fairway_machine_1',
    name: 'Fairway Machine (Tier 1)',
    description: 'Hit 60% or more Fairways in Regulation in an on-course round.',
    icon: 'Target',
    isUnlocked: (data: AchievementData) => data.rounds.some(r => r.roundType !== 'Indoor' && parseFloat(r.fairwaysInRegulation) >= 60),
  },
  {
    id: 'ach_fairway_machine_2',
    name: 'Fairway Machine (Tier 2)',
    description: 'Hit 70% or more Fairways in Regulation in an on-course round.',
    icon: 'Target',
    isUnlocked: (data: AchievementData) => data.rounds.some(r => r.roundType !== 'Indoor' && parseFloat(r.fairwaysInRegulation) >= 70),
    dependsOn: 'ach_fairway_machine_1',
  },
  {
    id: 'ach_fairway_machine_3',
    name: 'Fairway Machine (Tier 3)',
    description: 'Hit 80% or more Fairways in Regulation in an on-course round.',
    icon: 'Trophy',
    isUnlocked: (data: AchievementData) => data.rounds.some(r => r.roundType !== 'Indoor' && parseFloat(r.fairwaysInRegulation) >= 80),
    dependsOn: 'ach_fairway_machine_2',
  },
  {
    id: 'ach_green_seeker_1',
    name: 'Green Seeker (Tier 1)',
    description: 'Hit 50% or more Greens in Regulation in an on-course round.',
    icon: 'TrendingUp',
    isUnlocked: (data: AchievementData) => data.rounds.some(r => r.roundType !== 'Indoor' && parseFloat(r.greensInRegulation) >= 50),
  },
  {
    id: 'ach_green_seeker_2',
    name: 'Green Seeker (Tier 2)',
    description: 'Hit 60% or more Greens in Regulation in an on-course round.',
    icon: 'TrendingUp',
    isUnlocked: (data: AchievementData) => data.rounds.some(r => r.roundType !== 'Indoor' && parseFloat(r.greensInRegulation) >= 60),
    dependsOn: 'ach_green_seeker_1',
  },
  {
    id: 'ach_green_seeker_3',
    name: 'Green Seeker (Tier 3)',
    description: 'Hit 70% or more Greens in Regulation in an on-course round.',
    icon: 'Trophy',
    isUnlocked: (data: AchievementData) => data.rounds.some(r => r.roundType !== 'Indoor' && parseFloat(r.greensInRegulation) >= 70),
    dependsOn: 'ach_green_seeker_2',
  },
  {
    id: 'ach_sand_save_specialist_1',
    name: 'Sand Save Specialist (Tier 1)',
    description: 'Achieve 55% or more Sand Saves in an on-course round.',
    icon: 'Shield',
    isUnlocked: (data: AchievementData) => data.rounds.some(r => {
      if (r.roundType === 'Indoor') return false;
      const attempted = parseInt(r.sandSavesAttempted);
      if (attempted > 0) {
        const made = parseInt(r.sandSavesMade);
        return (made / attempted) * 100 >= 55;
      }
      return false;
    }),
  },
  {
    id: 'ach_sand_save_specialist_2',
    name: 'Sand Save Specialist (Tier 2)',
    description: 'Achieve 75% or more Sand Saves in an on-course round.',
    icon: 'Shield',
    isUnlocked: (data: AchievementData) => data.rounds.some(r => {
      if (r.roundType === 'Indoor') return false;
      const attempted = parseInt(r.sandSavesAttempted);
      if (attempted > 0) {
        const made = parseInt(r.sandSavesMade);
        return (made / attempted) * 100 >= 75;
      }
      return false;
    }),
    dependsOn: 'ach_sand_save_specialist_1',
  },
  {
    id: 'ach_sand_save_specialist_3',
    name: 'Sand Save Specialist (Tier 3)',
    description: 'Achieve 100% Sand Saves in an on-course round (min. 2 attempts).',
    icon: 'Trophy',
    isUnlocked: (data: AchievementData) => data.rounds.some(r => {
      if (r.roundType === 'Indoor') return false;
      const attempted = parseInt(r.sandSavesAttempted);
      if (attempted >= 2) {
        const made = parseInt(r.sandSavesMade);
        return (made / attempted) * 100 === 100;
      }
      return false;
    }),
    dependsOn: 'ach_sand_save_specialist_2',
  },
  {
    id: 'ach_one_putt_master',
    name: 'One-Putt Master',
    description: 'Make 5 or more one-putts in a single on-course round.',
    icon: 'CircleDot',
    isUnlocked: (data: AchievementData) => data.rounds.some(r => r.roundType !== 'Indoor' && parseInt(r.onePutts) >= 5),
  },
  {
    id: 'ach_no_3_putts_18_holes',
    name: 'Flawless Flatstick',
    description: 'Complete an 18-hole on-course round with zero 3-putts.',
    icon: 'CheckCircle',
    isUnlocked: (data: AchievementData) => data.rounds.some(r => r.roundType !== 'Indoor' && r.holesPlayed === '18' && parseInt(r.threePuttsOrMore) === 0),
  },
  // Course Explorer
   {
    id: 'ach_course_explorer_1',
    name: 'Course Explorer (Tier 1)',
    description: 'Play 5 different golf courses.',
    icon: 'Map',
    isUnlocked: (data: AchievementData) => new Set(data.rounds.map(r => r.courseName)).size >= 5,
    progress: (data: AchievementData) => ({ current: new Set(data.rounds.map(r => r.courseName)).size, target: 5, unit: 'courses' }),
  },
  {
    id: 'ach_course_explorer_2',
    name: 'Course Explorer (Tier 2)',
    description: 'Play 10 different golf courses.',
    icon: 'Map',
    isUnlocked: (data: AchievementData) => new Set(data.rounds.map(r => r.courseName)).size >= 10,
    progress: (data: AchievementData) => ({ current: new Set(data.rounds.map(r => r.courseName)).size, target: 10, unit: 'courses' }),
    dependsOn: 'ach_course_explorer_1',
  },
  {
    id: 'ach_course_explorer_3',
    name: 'Course Explorer (Tier 3)',
    description: 'Play 15 different golf courses.',
    icon: 'Trophy',
    isUnlocked: (data: AchievementData) => new Set(data.rounds.map(r => r.courseName)).size >= 15,
    progress: (data: AchievementData) => ({ current: new Set(data.rounds.map(r => r.courseName)).size, target: 15, unit: 'courses' }),
    dependsOn: 'ach_course_explorer_2',
  },
  // Indoor Practice
  {
    id: 'ach_sim_specialist_1',
    name: 'Simulator Specialist (Tier 1)',
    description: 'Log 5 indoor rounds.',
    icon: 'PlayCircle',
    isUnlocked: (data: AchievementData) => data.rounds.filter(r => r.roundType === 'Indoor').length >= 5,
    progress: (data: AchievementData) => ({ current: data.rounds.filter(r => r.roundType === 'Indoor').length, target: 5, unit: 'rounds' }),
  },
    {
    id: 'ach_sim_specialist_2',
    name: 'Simulator Specialist (Tier 2)',
    description: 'Log 10 indoor rounds.',
    icon: 'PlayCircle',
    isUnlocked: (data: AchievementData) => data.rounds.filter(r => r.roundType === 'Indoor').length >= 10,
    progress: (data: AchievementData) => ({ current: data.rounds.filter(r => r.roundType === 'Indoor').length, target: 10, unit: 'rounds' }),
    dependsOn: 'ach_sim_specialist_1',
  },
  {
    id: 'ach_sim_specialist_3',
    name: 'Simulator Specialist (Tier 3)',
    description: 'Log 25 indoor rounds.',
    icon: 'Trophy',
    isUnlocked: (data: AchievementData) => data.rounds.filter(r => r.roundType === 'Indoor').length >= 25,
    progress: (data: AchievementData) => ({ current: data.rounds.filter(r => r.roundType === 'Indoor').length, target: 25, unit: 'rounds' }),
    dependsOn: 'ach_sim_specialist_2',
  },
  // Practice Dedication
  {
    id: 'ach_practice_pro_1',
    name: 'Practice Pro (Tier 1)',
    description: 'Complete 10 practice drills with reflections.',
    icon: 'ListChecks',
    isUnlocked: (data: AchievementData) => data.journalEntries.filter(entry => entry.drillName !== 'User Round Reflection' && entry.drillName !== "Coach's response and advice" && entry.drillName !== "Check in with Coach").length >= 10,
    progress: (data: AchievementData) => ({ current: data.journalEntries.filter(entry => entry.drillName !== 'User Round Reflection' && entry.drillName !== "Coach's response and advice" && entry.drillName !== "Check in with Coach").length, target: 10, unit: 'drills' }),
  },
  {
    id: 'ach_practice_pro_2',
    name: 'Practice Pro (Tier 2)',
    description: 'Complete a total of 25 practice drills.',
    icon: 'ListChecks',
    isUnlocked: (data: AchievementData) => data.completedDrillHistory.reduce((sum, h) => sum + h.recurrenceScore, 0) >= 25,
    progress: (data: AchievementData) => ({ current: data.completedDrillHistory.reduce((sum, h) => sum + h.recurrenceScore, 0), target: 25, unit: 'drills' }),
    dependsOn: 'ach_practice_pro_1',
  },
  {
    id: 'ach_practice_pro_3',
    name: 'Practice Pro (Tier 3)',
    description: 'Complete a total of 50 practice drills.',
    icon: 'ListChecks',
    isUnlocked: (data: AchievementData) => data.completedDrillHistory.reduce((sum, h) => sum + h.recurrenceScore, 0) >= 50,
    progress: (data: AchievementData) => ({ current: data.completedDrillHistory.reduce((sum, h) => sum + h.recurrenceScore, 0), target: 50, unit: 'drills' }),
    dependsOn: 'ach_practice_pro_2',
  },
  {
    id: 'ach_practice_pro_4',
    name: 'Practice Pro (Tier 4)',
    description: 'Complete a total of 100 practice drills.',
    icon: 'Trophy',
    isUnlocked: (data: AchievementData) => data.completedDrillHistory.reduce((sum, h) => sum + h.recurrenceScore, 0) >= 100,
    progress: (data: AchievementData) => ({ current: data.completedDrillHistory.reduce((sum, h) => sum + h.recurrenceScore, 0), target: 100, unit: 'drills' }),
    dependsOn: 'ach_practice_pro_3',
  },
  {
    id: 'ach_library_unlocked',
    name: 'Library Unlocked!',
    description: 'Complete 10 practice drills with reflections to unlock the full Drill Library.',
    icon: 'LibrarySquare',
    isUnlocked: (data: AchievementData) => data.journalEntries.filter(entry => entry.drillName !== 'User Round Reflection' && entry.drillName !== "Coach's response and advice" && entry.drillName !== "Check in with Coach").length >= 10,
    progress: (data: AchievementData) => ({ current: data.journalEntries.filter(entry => entry.drillName !== 'User Round Reflection' && entry.drillName !== "Coach's response and advice" && entry.drillName !== "Check in with Coach").length, target: 10, unit: 'drills' }),
  },
  {
    id: 'ach_mental_fortitude',
    name: 'Mental Fortitude',
    description: 'Complete your first Mental Game drill.',
    icon: 'Brain',
    isUnlocked: (data: AchievementData) => {
      const completedMentalDrill = data.completedDrillHistory.find(h => {
        const drill = initialDrills.find(d => d.id === h.drillId);
        return drill?.category === 'Mental Game';
      });
      return !!completedMentalDrill;
    },
    progress: (data: AchievementData) => {
      const completedMentalDrill = data.completedDrillHistory.find(h => {
        const drill = initialDrills.find(d => d.id === h.drillId);
        return drill?.category === 'Mental Game';
      });
      return { current: completedMentalDrill ? 1 : 0, target: 1, unit: 'drill' };
    },
  },
];
